
package checkservice.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "FNSNDSCAWS2", targetNamespace = "http://ws.unisoft", wsdlLocation = "http://npchk.nalog.ru/FNSNDSCAWS_2?wsdl")
public class FNSNDSCAWS2
    extends Service
{

    private final static URL FNSNDSCAWS2_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(checkservice.wsdl.FNSNDSCAWS2 .class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = checkservice.wsdl.FNSNDSCAWS2 .class.getResource(".");
            url = new URL(baseUrl, "http://npchk.nalog.ru/FNSNDSCAWS_2?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://npchk.nalog.ru/FNSNDSCAWS_2?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        FNSNDSCAWS2_WSDL_LOCATION = url;
    }

    public FNSNDSCAWS2(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FNSNDSCAWS2() {
        super(FNSNDSCAWS2_WSDL_LOCATION, new QName("http://ws.unisoft", "FNSNDSCAWS2"));
    }

    /**
     * 
     * @return
     *     returns FNSNDSCAWS2Port
     */
    @WebEndpoint(name = "FNSNDSCAWS2_Port")
    public FNSNDSCAWS2Port getFNSNDSCAWS2Port() {
        return super.getPort(new QName("http://ws.unisoft", "FNSNDSCAWS2_Port"), FNSNDSCAWS2Port.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FNSNDSCAWS2Port
     */
    @WebEndpoint(name = "FNSNDSCAWS2_Port")
    public FNSNDSCAWS2Port getFNSNDSCAWS2Port(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.unisoft", "FNSNDSCAWS2_Port"), FNSNDSCAWS2Port.class, features);
    }

}
